name: DVPlus
version: ${version}
main: me.st4r.myplugin.DVPlus
description: Adds new vanilla-inspired mechanics to Minecraft.
authors: [st4r]

commands:
  parrot:
    description: Control your messenger parrot
    usage: /parrot deliver <PlayerName>
  gcg:
    description: Control the GCG automation grid mode
    usage: /gcg <mode|transfer>
  displaybattery:
    description: Toggle live battery readouts when you change chunks
    usage: /displaybattery
