name: DVPlus
version: ${version}
main: me.st4r.myplugin.DVPlus
description: Adds new vanilla-inspired mechanics to Minecraft.
authors: [st4r]

commands:
  parrot:
    description: Control your messenger parrot
    usage: /parrot deliver <PlayerName>
  gcg:
    description: Control GCG chunk mode and electricity transfer
    usage: /gcg mode <0-4> or /gcg transfer <fromX> <fromZ> <toX> <toZ> [amount]
  batterydisplay:
    description: Toggle chunk battery display when moving between chunks
    usage: /batterydisplay
