name: Dams's Vanilla+
version: ${version}
main: me.st4r.myplugin.DVPlus
description: Adds new vanilla-inspired mechanics to Minecraft
authors: [st4r]

commands:
  parrot:
    description: Control your messenger parrot
    usage: /parrot deliver <PlayerName>
